<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Contracts/Microservice.StorageGateway.Contracts.csproj" />
    <ProjectReference Include="..\Application\Microservice.StorageGateway.Application.csproj" />
    <ProjectReference Include="..\Domain\Microservice.StorageGateway.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
