<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/Microservice.StorageGateway.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis" Version="1.69.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.69.0.3783" />
  </ItemGroup>

</Project>
